### PR TITLE
Tidy columns

### PR DESCRIPTION
**Pull request by KulaGGin**
Made columns more tidy:
tekkenbotprime_2018-03-30_00-54-35

Vs default:
chrome_2018-03-30_01-05-03

### CODE REVIEW

**Comment by WAZAAAAA0** [comment]
it's tidy but I'm not convinced by the smaller font size to be fair :confused:

**Comment by Pobega** [comment]
@KulaGGin I think this looks a lot better personally, I'd recommend trying to get it working as a toggleable option instead of changing the default layout. Then @WAZAAAAA0 wouldn't have to pick  ¯\_(ツ)_/¯

**Comment by Lanqu** [comment]
Ye, please merge this

**Comment by WAZAAAAA0** [comment]
alright I'm gonna merge it the next game patch, and if people are butthurt about it I'll just undo it

**Pull request merged**
