### PR TITLE
Fix for OPPONENT_SIDE

### PR DESCRIPTION
**Pull request by Sam-Si**

### CODE REVIEW

**Comment by Sam-Si** [comment]
Fix for the issue
bot_facing variable seems to be either always true or always false. Needs a fix

**Comment by WAZAAAAA0** [comment]
I'm not convinced
the address you found changes constantly every time a player switches side in the middle of a fight, which is a different behavior than what we're used to, and somehow the TekkenBot crashed a couple of times when I tried it

**Comment by Sam-Si** [comment]
@WAZAAAAA0 Umm that's weird because it seems to work perfectly on my machine.
Please don't merge it then. I don't want anyone complaining. I am happy :p

**Comment by KulaGGin** [comment]
Thiis would be nice to see a fix for opponent side, often it shows frame data on the left side for an opponent, even considering you're on the left side in the game.

**Pull request closed without merging**
